name: Reusable inner

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Parámetros de entrada
        env:
          PARAMS_ENTERED: ${{ toJSON(github.event.inputs) }}
          INPUT_PARAMS_ENTERED: ${{ toJSON(inputs) }}
          SECRET_PARAMS_ENTERED: ${{ toJSON(secrets) }}
        run: |
          echo $PARAMS_ENTERED
          echo $INPUT_PARAMS_ENTERED
          echo $SECRET_PARAMS_ENTERED
      
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
          
          
  do-something-else:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello"
