# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: App Name
        required: true
        type: string

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Parámetros de entrada
        env:
          PARAMS_ENTERED: ${{ toJSON(github.event.inputs) }}
          INPUT_PARAMS_ENTERED: ${{ toJSON(inputs) }}
          SECRET_PARAMS_ENTERED: ${{ toJSON(secrets) }}
        run: |
          echo $PARAMS_ENTERED
          echo $INPUT_PARAMS_ENTERED
          echo $SECRET_PARAMS_ENTERED

  docker:
    uses: ./.github/workflows/deploy_reusable.yml
    with:
      image_name: ${{ github.event.inputs.app-name }}
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}

  validate-data:
    name: ✅ Validate
    runs-on: ubuntu-latest
    steps:
    - name: Parámetros de entrada
      env:
        PARAMS_ENTERED: ${{ toJSON(github.event.inputs) }}
      run: echo $PARAMS_ENTERED